export const ADD_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const INCREASE_ITEM_COUNT = "INCREASE_ITEM_COUNT";
export const DECREASE_ITEM_COUNT = "DECREASE_ITEM_COUNT";
export const SUB_TOTAL = "SUB_TOTAL";
